### ISSUE TITLE
Incorrect binary in linux amd64 release

### ISSUE THREAD

**Issue by mplachter** [blakelead/couchbase_exporter#39] opened 2019-06-24 02:40 UTC
# Wrong binary in tar.gz for linux amd64.

The `linux-amd64.tar.gz` form the release page does not run on `alpine:3.9.3`.

However if I clone down the repo and build the binary `env GOOS=linux GOARCH=amd64 go build ./couchbase_exporter.go` it runs on `alpine` no problem.

This leads me to believe the release tar.gz does not have the correct binary tar.gz.

**Comment by blakelead** [comment] 2019-06-24 14:29
Hey @mplachter,

Thanks for reporting this, I'll look into it

**Comment by blakelead** [comment] 2019-09-26 19:56
Hello @mplachter ,

I'm sorry for the really long delay!

The issue is now fixed in the master branch and in 0.9.2 release.

**Closed as completed** 2019-10-25 15:13 UTC
Labels: status: completed, type: bug
